[net]
git-fetch-with-cli = true
retry = 10

[http]
timeout = 60

[registries.crates-io]
protocol = "sparse"

[profile.release]
debug = true

[alias]
test-e2e-local = "test --test e2e_tests --no-default-features --features local -- --test-threads=1 --nocapture"